import Ionicons from '@expo/vector-icons/Ionicons';
import { router } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable } from '@/components/common/AnimatedPressable';
import { Screen } from '@/components/common/Screen';
import { mockDashboard } from '@/data/mockDashboard';
import { colors, radius, spacing, typography } from '@/theme';

export function StudySessionScreen() {
  const focus = mockDashboard.currentFocus;
  return <Screen><View style={styles.top}><AnimatedPressable onPress={() => router.back()} accessibilityRole="button" accessibilityLabel="Sair da sessão" style={styles.back}><Ionicons name="close" size={24} color={colors.textPrimary} /></AnimatedPressable><Text style={styles.topLabel}>Sessão de estudos</Text></View><View style={styles.main}><Text style={styles.eyebrow}>FOCO ATUAL</Text><Text style={styles.subject}>{focus.subject}</Text><Text style={styles.topic}>{focus.topic}</Text><View style={styles.timer}><Text style={styles.time}>45:00</Text><Text style={styles.timerLabel}>cronômetro visual · não iniciado</Text></View><View style={styles.plan}><Ionicons name="time-outline" size={20} color={colors.atlas} /><Text style={styles.planText}>{focus.estimatedMinutes} minutos planejados</Text></View></View><View style={styles.actions}><SessionButton label="Pausar" icon="pause" onPress={() => undefined} /><SessionButton label="Concluir" icon="checkmark" primary onPress={() => router.back()} /><SessionButton label="Sair" icon="exit-outline" onPress={() => router.back()} /></View><Text style={styles.note}>Nesta versão, os controles demonstram apenas o fluxo de navegação.</Text></Screen>;
}

function SessionButton({ label, icon, primary, onPress }: { label: string; icon: React.ComponentProps<typeof Ionicons>['name']; primary?: boolean; onPress: () => void }) { return <AnimatedPressable onPress={onPress} accessibilityRole="button" accessibilityLabel={label} style={[styles.action, primary && styles.primary]}><Ionicons name={icon} size={23} color={primary ? colors.background : colors.textPrimary} /><Text style={[styles.actionLabel, primary && styles.primaryLabel]}>{label}</Text></AnimatedPressable>; }

const styles = StyleSheet.create({ top: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, back: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface }, topLabel: { ...typography.bodyStrong, color: colors.textSecondary }, main: { minHeight: 470, alignItems: 'center', justifyContent: 'center', paddingVertical: spacing.xxl }, eyebrow: { ...typography.label, color: colors.atlas }, subject: { ...typography.screenTitle, color: colors.textPrimary, marginTop: spacing.sm, textAlign: 'center' }, topic: { ...typography.body, color: colors.textSecondary, textAlign: 'center', maxWidth: 340 }, timer: { width: 240, height: 240, borderRadius: 120, alignItems: 'center', justifyContent: 'center', marginVertical: spacing.xxl, backgroundColor: colors.surface, borderWidth: 2, borderColor: colors.atlas }, time: { fontSize: 52, lineHeight: 60, fontWeight: '300', color: colors.textPrimary, fontVariant: ['tabular-nums'] }, timerLabel: { ...typography.caption, color: colors.textMuted, marginTop: spacing.xs }, plan: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs }, planText: { ...typography.bodyStrong, color: colors.textSecondary }, actions: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: spacing.sm }, action: { minWidth: 98, minHeight: 58, paddingHorizontal: spacing.md, borderRadius: radius.pill, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, primary: { backgroundColor: colors.atlas, borderColor: colors.atlas }, actionLabel: { ...typography.bodyStrong, color: colors.textPrimary }, primaryLabel: { color: colors.background }, note: { ...typography.caption, color: colors.textMuted, textAlign: 'center' } });
